# Generated by Django 6.0.6 on 2026-07-16 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_problem"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Problem",
        ),
    ]
